### ISSUE TITLE
Image Field Mapping Breaks Rule Logic

### ISSUE THREAD

**Issue by otoqui** [7RedViolin/pySigma-backend-sentinelone#2]
The "Image" field in Sigma is being mapped to "TgtProcName" in SentinelOne Deep Visibility queries. This may break in scenarios where modifiers such as "endswith" are used in the Sigma rule, because the TgtProcName field only contains the binary name.

A Sigma rule might specify something like: Image|endswith: '\cmd.exe', which when translated to a SentinelOne Deep Visibility query using this plugin yields the result: TgtProcName endswithCIS "\\\\cmd.exe", which won't produce a desired match.

Using a slightly modified version of the "Data Copied To Clipboard Via Clip.EXE" Sigma rule published here as an example: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_clip_execution.yml

Sigma:
```
title: Data Copied To Clipboard Via Clip.EXE
id: 793d0218-a6b6-4fcf-8a64-60474303c915
status: test
description: Detects the execution of clip.exe in order to copy data to the clipboard. Adversaries may collect data stored in the clipboard from users copying information within or between applications.
references:
    - https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/clip
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1115/T1115.md
author: frack113, otoqui
date: 2021/07/27
modified: 2023/04/27
tags:
    - attack.collection
    - attack.t1115
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        - Image|endswith: '\clip.exe'
    #   - OriginalFileName: clip.exe
    condition: selection
falsepositives:
    - Unknown
level: low
```

S1QL:
```
EventType = "Process Creation" AND (EndpointOS = "windows" AND TgtProcName endswithCIS "\\clip.exe")
```
![image](https://user-images.githubusercontent.com/131987202/234941655-08215d47-4947-4cf0-bf41-6596fde52091.png)

Corrected S1QL:
![image](https://user-images.githubusercontent.com/131987202/234941981-637454ef-97e2-4f89-915a-d9ae64c04699.png)

The rule is syntactically valid, but because the *Name fields in SentinelOne only contain a value like "cmd.exe", a query for *Name endswithCIS "\\\\cmd.exe" will _not_ return a match as intended. **NOTE: The double backslash is also an issue, since SentinelOne treats that as an escape character. The correct value would be endswithCIS "\cmd.exe":**
![image](https://user-images.githubusercontent.com/131987202/234942234-1ce41420-a6b6-400f-aa25-ae1735dbd811.png)

With this in mind, a better candidate for the target field when mapping the Image field might be "TgtProcImagePath". The same goes for the "ParentImage" field in Sigma, which instead of being mapped to "SrcProcName" or "SrcProcParentName" should be mapped to "SrcProcImagePath" or "SrcProcParentImagePath" respectively.
